nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']  
        allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization']  
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']  
        max_age: 3600  
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']  
            max_age: 3600
